name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --no-audit --no-fund
      - name: Type check
        run: npx tsc -p tsconfig.json --noEmit
      - name: Lint
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Cache Next build
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
            node_modules/.cache
          key: next-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            next-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Set base path for Pages
        run: |
          REPO_NAME="${{ github.event.repository.name }}"
          OWNER="${{ github.repository_owner }}"
          if [ "$REPO_NAME" = "${OWNER}.github.io" ]; then
            echo "NEXT_PUBLIC_BASE_PATH=" >> $GITHUB_ENV
            echo "Using user/org page at root /"
          else
            echo "NEXT_PUBLIC_BASE_PATH=/$REPO_NAME" >> $GITHUB_ENV
            echo "Using project page base path /$REPO_NAME"
          fi

      - name: Build static site (Next export)
        run: |
          echo "Base path: ${NEXT_PUBLIC_BASE_PATH}"
          npx next build
          if [ ! -d out ]; then
            echo "'out' not found after build; attempting next export"
            npx next export || true
          fi

      - name: Add 404 fallback and .nojekyll
        run: |
          mkdir -p out
          if [ ! -f out/404.html ] && [ -f out/index.html ]; then
            cp out/index.html out/404.html
          fi
          touch out/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
